"""Source-tracked time-standard lookup for calendar benchmark notes.

USA Swimming motivational standards are loaded from ``data/motivational_standards.json``
(generated by ``scripts/extract_motivational_standards.py`` from the official age-group
PDF). The catalog covers both genders, all three courses (SCY/SCM/LCM), and all five
two-year age groups (10 & under through 17-18). Swimmer gender and course are read off
the event name; the swimmer's age is mapped to its two-year band. A separate Arizona LSC
table (AZSI) and an advanced post-AAAA ladder (``data/advanced_standards.json``) layer on
top for the cases they cover.
"""

from __future__ import annotations

from dataclasses import dataclass
import json
from pathlib import Path
import re


SOURCES = [
    {
        "name": "USA Swimming 2024-2028 Motivational Standards (two-year age group)",
        "url": "https://www.usaswimming.org/times/popular-resources/motivational-times",
    },
    {
        "name": "AZSI 2025-2026 Age Group State Qualifying Time Standards",
        "url": "https://www.azswimming.org/azswimming/UserFiles/File/azsi-age-group-state-qualifying-time-standards-2025-2026_080831.pdf",
    },
    {
        "name": "AZSI 2025-2026 Age Group Regional Qualifying Time Standards",
        "url": "https://www.azswimming.org/azswimming/UserFiles/File/azsi-age-group-regional-qualifying-time-standards-2025-2026_068948.pdf",
    },
    {
        "name": "AZSI 2025-2026 Senior State Qualifying Time Standards",
        "url": "https://www.azswimming.org/azswimming/UserFiles/File/azsi-senior-state-qualifying-time-standards-2025-2026_093733.pdf",
    },
    {
        "name": "AZSI 2025-2026 Senior Regional Qualifying Time Standards",
        "url": "https://www.azswimming.org/azswimming/UserFiles/File/azsi-senior-regional-qualifying-time-standards-2025-2026_043032.pdf",
    },
    {
        "name": "2026 Four Corners Spring Speedo Sectional Qualifying Time Standards",
        "url": "https://www.gomotionapp.com/azseals/__doc__/211074_4_2026-speedo-sectionals-four-corners-final.pdf",
    },
    {
        "name": "2026 Western Region Summer Speedo Sectional Qualifying Time Standards",
        "url": "https://www.gomotionapp.com/wzone/UserFiles/Image/QuickUpload/2026-speedo-sectionals---vtime-standards_099437.pdf",
    },
]

# AZSI Senior standards apply to ages 15-18 within this app: the AZSI Age Group bands cover 14
# and under, and the app's benchmark scope tops out at 18 (USA-S motivational bands end at
# 17-18). The Senior documents themselves carry no age dimension -- one cut per event -- and the
# meet flyer's eligibility states no age floor or ceiling, so 15-18 is the app-scoped slice that
# complements Age Group with no gap or overlap at the 14/15 boundary.
SENIOR_AGE_MIN = 15
SENIOR_AGE_MAX = 18

# Slowest -> fastest.
TIER_ORDER = ["B", "BB", "A", "AA", "AAA", "AAAA"]

# Distances longest-first so the regex prefers "1650" over the "50" inside it.
KNOWN_DISTANCES = ("1650", "1500", "1000", "800", "500", "400", "200", "100", "50", "25")


@dataclass(frozen=True)
class StandardResult:
    event_key: str
    usa_summary: str
    lsc_summary: str
    advanced_summary: str | None
    confidence_summary: str
    # Speedo Sectional targets (Four Corners Spring / Western Region Summer), AZ swimmers, age-open.
    # None when out of scope (non-AZ, or the event has no Sectional cut). New and last so existing
    # positional constructions stay valid.
    sectional_summary: str | None = None


def parse_time(value: str) -> float | None:
    value = value.strip().upper().rstrip("YLS")
    if value in {"", "NT"}:
        return None
    parts = value.split(":")
    try:
        if len(parts) == 1:
            return float(parts[0])
        if len(parts) == 2:
            return int(parts[0]) * 60 + float(parts[1])
    except ValueError:
        return None
    return None


def format_time(seconds: float) -> str:
    minutes = int(seconds // 60)
    rest = seconds - minutes * 60
    if minutes:
        return f"{minutes}:{rest:05.2f}"
    return f"{rest:.2f}"


def canonical_event_key(event_name: str) -> str:
    """Normalize an event name to a '<distance> <stroke>' key, e.g. '200 free', '400 im'.

    Age-group tokens that contain digits ('11-12', '12 & Under', '13 & Over') are stripped
    first so they can't be mistaken for the event distance, which otherwise trips up the
    longer freestyle distances (e.g. the '50' inside '1650').
    """
    text = re.sub(r"\s+", " ", event_name.lower())
    text = re.sub(r"\d+\s*&\s*(?:under|over)", " ", text)
    text = re.sub(r"\b\d{1,2}\s*-\s*\d{1,2}\b", " ", text)

    distance = None
    match = re.search(r"\b(" + "|".join(KNOWN_DISTANCES) + r")\b", text)
    if match:
        distance = match.group(1)

    if "relay" in text:
        stroke = "medley relay" if "medley" in text or "med-r" in text else "free relay"
    elif "free" in text:
        stroke = "free"
    elif "back" in text:
        stroke = "back"
    elif "breast" in text:
        stroke = "breast"
    elif "fly" in text or "butterfly" in text:
        stroke = "fly"
    elif re.search(r"\bim\b", text) or "individual medley" in text or "medley" in text:
        stroke = "im"
    else:
        stroke = None

    if distance and stroke:
        return f"{distance} {stroke}"
    return text.strip()


def event_gender(event_name: str) -> str | None:
    text = event_name.lower()
    if re.search(r"\b(girls|women)\b", text):
        return "girls"
    if re.search(r"\b(boys|men)\b", text):
        return "boys"
    return None


def event_course(event_name: str) -> str | None:
    """Read the pool course off the event name (Hy-Tek wording: 'LC Meter', 'SC Meter', 'SC Yard')."""
    text = event_name.lower()
    if "yard" in text or re.search(r"\bscy\b", text):
        return "SCY"
    if re.search(r"\bsc\s*meter", text) or re.search(r"\bscm\b", text):
        return "SCM"
    if re.search(r"\blc\s*meter", text) or re.search(r"\blcm\b", text) or "long course" in text:
        return "LCM"
    return None


def parse_age(age: str | int | None) -> int | None:
    if isinstance(age, int):
        return age
    match = re.search(r"\d{1,2}", str(age or ""))
    return int(match.group(0)) if match else None


def age_band(age: int | None) -> str | None:
    """Map a swimmer's actual age to its USA Swimming two-year motivational band.

    Returns None for ages the motivational standards do not cover (19 and older), so the
    caller reports 'not configured' rather than comparing against an inapplicable group.
    """
    if age is None:
        return None
    if age <= 10:
        return "10 & under"
    if age <= 12:
        return "11-12"
    if age <= 14:
        return "13-14"
    if age <= 16:
        return "15-16"
    if age <= 18:
        return "17-18"
    return None


ROOT = Path(__file__).resolve().parents[1]
MOTIVATIONAL_STANDARDS_PATH = ROOT / "data" / "motivational_standards.json"
AZSI_STANDARDS_PATH = ROOT / "data" / "azsi_standards.json"
AZSI_SENIOR_STANDARDS_PATH = ROOT / "data" / "azsi_senior_standards.json"
SECTIONAL_STANDARDS_PATH = ROOT / "data" / "sectional_standards.json"
ADVANCED_STANDARDS_PATH = ROOT / "data" / "advanced_standards.json"


def load_motivational_catalog(path: Path = MOTIVATIONAL_STANDARDS_PATH) -> dict:
    """Load the course -> gender -> age band -> event -> tier catalog."""
    if not path.exists():
        return {}
    data = json.loads(path.read_text(encoding="utf-8"))
    return data.get("standards", {})


def load_azsi_catalog(path: Path = AZSI_STANDARDS_PATH) -> dict:
    """Load the AZSI course -> gender -> age band -> event -> {state, regional} catalog."""
    if not path.exists():
        return {}
    data = json.loads(path.read_text(encoding="utf-8"))
    return data.get("standards", {})


def load_azsi_senior_catalog(path: Path = AZSI_SENIOR_STANDARDS_PATH) -> dict:
    """Load the AZSI Senior course -> gender -> event -> {state, regional} catalog.

    Unlike the Age Group catalog there is no age-band level: Senior is one cut per
    event/course/gender, applied to ages 15-18 (see SENIOR_AGE_MIN/MAX).
    """
    if not path.exists():
        return {}
    data = json.loads(path.read_text(encoding="utf-8"))
    return data.get("standards", {})


def load_sectional_meets(path: Path = SECTIONAL_STANDARDS_PATH) -> list[dict]:
    """Load the Speedo Sectional meets as an ordered list of {key, name, standards} dicts.

    Each meet keeps its own course -> gender -> event -> {qualifying} catalog; the two meets are
    NOT merged so the app can label "Four Corners" and "Western Region Summer" distinctly.
    """
    if not path.exists():
        return []
    data = json.loads(path.read_text(encoding="utf-8"))
    meets = []
    for key, meet in data.get("meets", {}).items():
        meets.append({"key": key, "name": meet.get("name", key), "standards": meet.get("standards", {})})
    return meets


def load_advanced_catalog(path: Path = ADVANCED_STANDARDS_PATH) -> tuple[list[dict], dict[str, list[dict[str, str]]]]:
    if not path.exists():
        return [], {}
    data = json.loads(path.read_text(encoding="utf-8"))
    sources = data.get("sources", [])
    cuts = data.get("cuts", {})
    normalized: dict[str, list[dict[str, str]]] = {}
    for event_name, rows in cuts.items():
        key = canonical_event_key(event_name)
        normalized[key] = [row for row in rows if row.get("time")]
        normalized[key].sort(key=lambda row: parse_time(row["time"]) or -1, reverse=True)
    return sources, normalized


# Arizona LSC (AZSI) qualifying cuts, generated by scripts/extract_azsi_standards.py from the
# official 2025-2026 State and Regional PDFs. Two catalogs, both {state, regional} per cell,
# with State faster than Regional in every event (meeting the State cut removes Regional
# eligibility -- the swimmer swims up to State -- which lookup() reports as "State met"):
#   AZSI_STANDARDS         data/azsi_standards.json         course -> gender -> age band -> event
#                          Age Group bands 10 & under / 11-12 / 13-14 (ages 14 and under).
#   AZSI_SENIOR_STANDARDS  data/azsi_senior_standards.json  course -> gender -> event (no band)
#                          One Senior cut per event, applied to ages 15-18 (SENIOR_AGE_MIN/MAX).
# Together they cover ages 10-&-under through 18 with no gap or overlap at the 14/15 boundary.
#
# Speedo Sectionals (USA Swimming Championship Series) layer on top for AZ swimmers, age-open
# (the meet flyers gate purely on qualifying time, not age), from data/sectional_standards.json
# (generated by scripts/extract_sectional_standards.py). Two distinct meets -- Four Corners Spring
# and Western Region Summer -- each course -> gender -> event -> {qualifying}, kept separate so
# lookup() can name them individually. These are a tier above LSC (zone/section level), so they
# report on their own StandardResult.sectional_summary line rather than folding into lsc_summary.
MOTIVATIONAL_STANDARDS = load_motivational_catalog()
AZSI_STANDARDS = load_azsi_catalog()
AZSI_SENIOR_STANDARDS = load_azsi_senior_catalog()
SECTIONAL_MEETS = load_sectional_meets()
ADVANCED_SOURCES, ADVANCED_LADDER = load_advanced_catalog()
SOURCES.extend(ADVANCED_SOURCES)


def motivational_standards(
    course: str | None, gender: str | None, band: str | None, event_key: str
) -> dict[str, str] | None:
    if not (course and gender and band and event_key):
        return None
    return (
        MOTIVATIONAL_STANDARDS.get(course, {})
        .get(gender, {})
        .get(band, {})
        .get(event_key)
    )


def azsi_standard(
    course: str | None, gender: str | None, band: str | None, event_key: str
) -> dict[str, str] | None:
    if not (course and gender and band and event_key):
        return None
    return (
        AZSI_STANDARDS.get(course, {})
        .get(gender, {})
        .get(band, {})
        .get(event_key)
    )


def is_senior_age(age: int | None) -> bool:
    """True for ages the AZSI Senior standards cover (15-18); Age Group covers 14 and under."""
    return age is not None and SENIOR_AGE_MIN <= age <= SENIOR_AGE_MAX


def azsi_senior_standard(
    course: str | None, gender: str | None, event_key: str
) -> dict[str, str] | None:
    if not (course and gender and event_key):
        return None
    return (
        AZSI_SENIOR_STANDARDS.get(course, {})
        .get(gender, {})
        .get(event_key)
    )


def sectional_summary_line(
    course: str | None, gender: str | None, event_key: str, seed_seconds: float
) -> str | None:
    """Per-meet Speedo Sectional status for an event, or None if no meet offers it.

    The two meets are reported separately and by name (never as a single generic "Sectional"),
    each as "met" or "target" against its own qualifying cut. Only meets that actually list the
    event contribute -- e.g. the Spring meet omits the 50s of stroke, so those show Summer only.
    """
    if not (course and gender and event_key):
        return None
    gender_label = "Girls" if gender == "girls" else "Boys"
    parts: list[str] = []
    for meet in SECTIONAL_MEETS:
        cell = meet["standards"].get(course, {}).get(gender, {}).get(event_key)
        if not cell or "qualifying" not in cell:
            continue
        cut = parse_time(cell["qualifying"])
        if cut is None:
            continue
        status = "met" if seed_seconds <= cut else "target"
        parts.append(f"{meet['name']}: {status} {cell['qualifying']}")
    if not parts:
        return None
    return f"Sectional {gender_label} {course} -- " + "; ".join(parts)


def achieved_tier(seed_seconds: float, standards: dict[str, str]) -> tuple[str | None, str | None]:
    ordered = list(reversed(TIER_ORDER))  # AAAA (fastest) -> B
    for idx, tier in enumerate(ordered):
        cut = parse_time(standards[tier])
        if cut is not None and seed_seconds <= cut:
            next_tier = ordered[idx - 1] if idx > 0 else None
            return tier, next_tier
    return None, "B"


def unconfigured_reason(gender: str | None, course: str | None, band: str | None) -> str:
    if gender is None:
        return "USA-S: could not determine gender from the event name"
    if course is None:
        return "USA-S: could not determine course from the event name"
    if band is None:
        return "USA-S: not configured for this swimmer age"
    return "USA-S: standard not configured for this event"


def lookup(event_name: str, seed_time: str, state: str = "AZ", age: str | int | None = None) -> StandardResult:
    event_key = canonical_event_key(event_name)
    seed_seconds = parse_time(seed_time)
    swimmer_age = parse_age(age)
    gender = event_gender(event_name)
    course = event_course(event_name)
    band = age_band(swimmer_age)

    if seed_seconds is None:
        return StandardResult(
            event_key,
            "USA-S: seed time not parseable",
            "LSC: seed time not parseable",
            None,
            "Standards confidence: not calculated",
        )

    usa_standards = motivational_standards(course, gender, band, event_key)
    confidence_parts: list[str] = []
    advanced_summary: str | None = None

    if usa_standards:
        gender_label = "Girls" if gender == "girls" else "Boys"
        source_label = f"USA-S {band} {gender_label} {course}"
        tier, next_tier = achieved_tier(seed_seconds, usa_standards)
        if tier:
            if next_tier:
                usa_summary = f"{source_label}: {tier}; next {next_tier} {usa_standards[next_tier]}"
            else:
                usa_summary = f"{source_label}: AAAA"
                if gender == "girls" and course == "LCM":
                    advanced_summary = next_advanced_target(event_key, seed_seconds)
        else:
            usa_summary = f"{source_label}: below B; B target {usa_standards['B']}"
        confidence_parts.append("USA-S verified")
    else:
        usa_summary = unconfigured_reason(gender, course, band)
        confidence_parts.append("USA-S not configured")

    # Arizona LSC layer: AZ only. Age Group bands (10 & under, 11-12, 13-14) cover ages 14 and
    # under; the flat Senior catalog covers ages 15-18 (is_senior_age). Age Group is tried first
    # -- for 15-18 the age_band() result ("15-16"/"17-18") is absent from the Age Group catalog
    # so azsi_standard() returns None, and the Senior lookup supplies the cut instead. Both share
    # the {state, regional} shape, so the summary logic below is identical; only the label band
    # differs ("Senior" vs the age band).
    azsi = azsi_standard(course, gender, band, event_key) if state.upper() == "AZ" else None
    azsi_band_label = band
    if azsi is None and state.upper() == "AZ" and is_senior_age(swimmer_age):
        azsi = azsi_senior_standard(course, gender, event_key)
        azsi_band_label = "Senior"
    if azsi and "state" in azsi and "regional" in azsi:
        gender_label = "Girls" if gender == "girls" else "Boys"
        azsi_label = f"AZSI {azsi_band_label} {gender_label} {course}"
        state_cut = parse_time(azsi["state"])
        regional_cut = parse_time(azsi["regional"])
        if state_cut is not None and seed_seconds <= state_cut:
            lsc_summary = f"{azsi_label}: State met; State {azsi['state']}, Regional {azsi['regional']}"
        elif regional_cut is not None and seed_seconds <= regional_cut:
            lsc_summary = f"{azsi_label}: Regional met; State target {azsi['state']}, Regional {azsi['regional']}"
        else:
            lsc_summary = f"{azsi_label}: target State {azsi['state']}, Regional {azsi['regional']}"
        confidence_parts.append("AZSI verified")
    else:
        lsc_summary = "LSC: standards not configured for this state/event"
        confidence_parts.append("LSC not configured")

    if advanced_summary and advanced_summary.startswith("Beyond AAAA"):
        confidence_parts.append("advanced verified")
    elif advanced_summary:
        confidence_parts.append("advanced partial")

    # Speedo Sectional layer: AZ only, AGE-OPEN. The Four Corners Spring and Western Region Summer
    # meet flyers both define eligibility as "open to all athletes who ... have met the appropriate
    # qualifying times" -- registration plus an eligible LSC plus the time, with no age floor or
    # ceiling. So this is deliberately NOT gated to the 15-18 Senior range (that would be
    # convenience, not the published rule): any AZ swimmer whose event has a Sectional cut sees the
    # target, including ages the USA-S/AZSI layers can't classify (e.g. 19+). Reported on its own
    # line because Sectionals sit a tier above LSC; the two meets are named individually so they
    # never collapse into a generic "Sectional". Left off the confidence line to keep it stable.
    sectional_summary: str | None = None
    if state.upper() == "AZ":
        sectional_summary = sectional_summary_line(course, gender, event_key, seed_seconds)

    return StandardResult(
        event_key,
        usa_summary,
        lsc_summary,
        advanced_summary,
        f"Standards confidence: {', '.join(confidence_parts)}",
        sectional_summary,
    )


def next_advanced_target(event_key: str, seed_seconds: float) -> str | None:
    remaining: list[dict[str, str]] = []
    for row in ADVANCED_LADDER.get(event_key, []):
        cut = parse_time(row["time"])
        if cut is not None and seed_seconds > cut:
            remaining.append(row)
    if remaining:
        next_row = remaining[0]
        then_rows = remaining[1:5]
        summary = f"Beyond AAAA: next {next_row['name']} {next_row['time']}"
        if then_rows:
            then = ", ".join(f"{row['name']} {row['time']}" for row in then_rows)
            summary = f"{summary}; then {then}"
        return summary
    if event_key in ADVANCED_LADDER:
        return "Advanced standards loaded; swimmer has met all configured targets"
    return "Advanced cuts beyond AAAA are not configured for this event yet"
