"""Source-tracked time-standard lookup for calendar benchmark notes.

USA Swimming motivational standards are loaded from ``data/motivational_standards.json``
(generated by ``scripts/extract_motivational_standards.py`` from the official age-group
PDF). The catalog covers both genders, all three courses (SCY/SCM/LCM), and all five
two-year age groups (10 & under through 17-18). Swimmer gender and course are read off
the event name; the swimmer's age is mapped to its two-year band. A separate Arizona LSC
table (AZSI), the AZ Speedo Sectionals, and the national championship meets layer on top; the
post-AAAA "Beyond AAAA" ladder is built from the AZ Sectional + national datasets
(``data/sectional_standards.json`` + ``data/national_standards.json``), not the now-superseded
``data/advanced_standards.json``.
"""

from __future__ import annotations

from dataclasses import dataclass, field
import json
from pathlib import Path
import re


SOURCES = [
    {
        "name": "USA Swimming 2024-2028 Motivational Standards (two-year age group)",
        "url": "https://www.usaswimming.org/times/popular-resources/motivational-times",
    },
    {
        "name": "AZSI 2025-2026 Age Group State Qualifying Time Standards",
        "url": "https://www.azswimming.org/azswimming/UserFiles/File/azsi-age-group-state-qualifying-time-standards-2025-2026_080831.pdf",
    },
    {
        "name": "AZSI 2025-2026 Age Group Regional Qualifying Time Standards",
        "url": "https://www.azswimming.org/azswimming/UserFiles/File/azsi-age-group-regional-qualifying-time-standards-2025-2026_068948.pdf",
    },
    {
        "name": "AZSI 2025-2026 Senior State Qualifying Time Standards",
        "url": "https://www.azswimming.org/azswimming/UserFiles/File/azsi-senior-state-qualifying-time-standards-2025-2026_093733.pdf",
    },
    {
        "name": "AZSI 2025-2026 Senior Regional Qualifying Time Standards",
        "url": "https://www.azswimming.org/azswimming/UserFiles/File/azsi-senior-regional-qualifying-time-standards-2025-2026_043032.pdf",
    },
    {
        "name": "2026 Four Corners Spring Speedo Sectional Qualifying Time Standards",
        "url": "https://www.gomotionapp.com/azseals/__doc__/211074_4_2026-speedo-sectionals-four-corners-final.pdf",
    },
    {
        "name": "2026 Western Region Summer Speedo Sectional Qualifying Time Standards",
        "url": "https://www.gomotionapp.com/wzone/UserFiles/Image/QuickUpload/2026-speedo-sectionals---vtime-standards_099437.pdf",
    },
    {
        "name": "2026 TYR Futures Championships Time Standards",
        "url": "https://www.usaswimming.org/docs/default-source/timesdocuments/time-standards/2026/2026_tyrfutureschampionships_timestandards-2.pdf",
    },
    {
        "name": "2026 Speedo Summer Junior National Championships Time Standards",
        "url": "https://www.usaswimming.org/docs/default-source/timesdocuments/time-standards/2026/2026_speedojuniornationalchampionships_timestandards.pdf",
    },
    {
        "name": "2026 Toyota National Championships Time Standards",
        "url": "https://www.usaswimming.org/docs/default-source/timesdocuments/time-standards/2026/18077640025_events_2026_toyotanationalchampionships_timestandards.pdf",
    },
    {
        "name": "2026 Speedo Winter Junior Championships Time Standards",
        "url": "https://swimstandards.com/times/2026-speedo-winter-junior-championships-time-standards",
    },
    {
        "name": "2026 Toyota U.S. Open Time Standards",
        "url": "https://swimstandards.com/times/2026-toyota-us-open-time-standards",
    },
]

# National elite standards (Futures, Toyota Nationals, Summer/Winter Juniors, U.S. Open) are open
# to any USA Swimming member nationally -- NOT LSC-scoped like AZSI/Sectional, which only apply to
# Arizona swimmers. Age eligibility was verified against each meet's own announcement, not assumed:
#   - Futures / Toyota Nationals: no meet-wide age floor or ceiling. Their standards split into
#     two age brackets (18 & Under / 19 & Over) that together cover every age with no gap --
#     which bracket's cutoff to compare against, not who may enter.
#   - Summer Juniors / Winter Juniors: a real meet-wide ceiling -- "all athletes at the meet must
#     be 18 or under on the first day of the meet" -- covering both their Qualifying and Bonus
#     tiers (there is only one eligible population), unlike the age-open Sectional/Futures/Toyota
#     Nationals layers. Each meet's own age_ceiling (loaded from its JSON entry) carries this.
#   - Toyota U.S. Open: its Qualifying tier is age-open (no ceiling), but its Bonus tier alone is
#     18-and-under -- the one meet here where the two tiers have different age gates, tracked via
#     bonus_age_ceiling separately from age_ceiling.
# Winter Juniors and U.S. Open's official PDFs have zero extractable text (font glyphs rendered as
# vector outlines, confirmed with both pypdf and pdfplumber, no OCR tooling in this project), so
# both were instead sourced from swimstandards.com and saved as local CSV fixtures -- see
# scripts/extract_national_standards.py for the full extraction/verification notes.

# AZSI Senior standards apply to ages 15-18 within this app: the AZSI Age Group bands cover 14
# and under, and the app's benchmark scope tops out at 18 (USA-S motivational bands end at
# 17-18). The Senior documents themselves carry no age dimension -- one cut per event -- and the
# meet flyer's eligibility states no age floor or ceiling, so 15-18 is the app-scoped slice that
# complements Age Group with no gap or overlap at the 14/15 boundary.
SENIOR_AGE_MIN = 15
SENIOR_AGE_MAX = 18

# Slowest -> fastest.
TIER_ORDER = ["B", "BB", "A", "AA", "AAA", "AAAA"]

# Distances longest-first so the regex prefers "1650" over the "50" inside it.
KNOWN_DISTANCES = ("1650", "1500", "1000", "800", "500", "400", "200", "100", "50", "25")


@dataclass(frozen=True)
class StandardResult:
    event_key: str
    usa_summary: str
    lsc_summary: str
    advanced_summary: str | None
    confidence_summary: str
    # Speedo Sectional targets (Four Corners Spring / Western Region Summer), AZ swimmers, age-open.
    # None when out of scope (non-AZ, or the event has no Sectional cut). New and last so existing
    # positional constructions stay valid.
    sectional_summary: str | None = None
    # National elite targets (Futures, Toyota Nationals, Summer Juniors), any state/LSC. None
    # when out of scope (Summer Juniors' 18-and-under ceiling, or the event has no national cut).
    national_summary: str | None = None
    # Per-line source links so the display can turn each standard's label into a checkable link to
    # the document that specific number came from. Keyed by line name (usa/lsc/sectional/national/
    # advanced); each value is a list of {"label": <exact substring of that line>, "url": <source>}.
    # A display surface linkifies (web) or appends the URL as plain text (.ics) for whatever it shows.
    sources: dict[str, list[dict[str, str]]] = field(default_factory=dict)


def parse_time(value: str) -> float | None:
    value = value.strip().upper().rstrip("YLS")
    if value in {"", "NT"}:
        return None
    parts = value.split(":")
    try:
        if len(parts) == 1:
            return float(parts[0])
        if len(parts) == 2:
            return int(parts[0]) * 60 + float(parts[1])
    except ValueError:
        return None
    return None


def format_time(seconds: float) -> str:
    minutes = int(seconds // 60)
    rest = seconds - minutes * 60
    if minutes:
        return f"{minutes}:{rest:05.2f}"
    return f"{rest:.2f}"


def canonical_event_key(event_name: str) -> str:
    """Normalize an event name to a '<distance> <stroke>' key, e.g. '200 free', '400 im'.

    Age-group tokens that contain digits ('11-12', '12 & Under', '13 & Over') are stripped
    first so they can't be mistaken for the event distance, which otherwise trips up the
    longer freestyle distances (e.g. the '50' inside '1650').
    """
    text = re.sub(r"\s+", " ", event_name.lower())
    text = re.sub(r"\d+\s*&\s*(?:under|over)", " ", text)
    text = re.sub(r"\b\d{1,2}\s*-\s*\d{1,2}\b", " ", text)

    distance = None
    match = re.search(r"\b(" + "|".join(KNOWN_DISTANCES) + r")\b", text)
    if match:
        distance = match.group(1)

    if "relay" in text:
        stroke = "medley relay" if "medley" in text or "med-r" in text else "free relay"
    elif "free" in text:
        stroke = "free"
    elif "back" in text:
        stroke = "back"
    elif "breast" in text:
        stroke = "breast"
    elif "fly" in text or "butterfly" in text:
        stroke = "fly"
    elif re.search(r"\bim\b", text) or "individual medley" in text or "medley" in text:
        stroke = "im"
    else:
        stroke = None

    if distance and stroke:
        return f"{distance} {stroke}"
    return text.strip()


def event_gender(event_name: str) -> str | None:
    text = event_name.lower()
    if re.search(r"\b(girls|women)\b", text):
        return "girls"
    if re.search(r"\b(boys|men)\b", text):
        return "boys"
    return None


def event_course(event_name: str) -> str | None:
    """Read the pool course off the event name (Hy-Tek wording: 'LC Meter', 'SC Meter', 'SC Yard')."""
    text = event_name.lower()
    if "yard" in text or re.search(r"\bscy\b", text):
        return "SCY"
    if re.search(r"\bsc\s*meter", text) or re.search(r"\bscm\b", text):
        return "SCM"
    if re.search(r"\blc\s*meter", text) or re.search(r"\blcm\b", text) or "long course" in text:
        return "LCM"
    return None


def parse_age(age: str | int | None) -> int | None:
    if isinstance(age, int):
        return age
    match = re.search(r"\d{1,2}", str(age or ""))
    return int(match.group(0)) if match else None


def age_band(age: int | None) -> str | None:
    """Map a swimmer's actual age to its USA Swimming two-year motivational band.

    Returns None for ages the motivational standards do not cover (19 and older), so the
    caller reports 'not configured' rather than comparing against an inapplicable group.
    """
    if age is None:
        return None
    if age <= 10:
        return "10 & under"
    if age <= 12:
        return "11-12"
    if age <= 14:
        return "13-14"
    if age <= 16:
        return "15-16"
    if age <= 18:
        return "17-18"
    return None


ROOT = Path(__file__).resolve().parents[1]
MOTIVATIONAL_STANDARDS_PATH = ROOT / "data" / "motivational_standards.json"
AZSI_STANDARDS_PATH = ROOT / "data" / "azsi_standards.json"
AZSI_SENIOR_STANDARDS_PATH = ROOT / "data" / "azsi_senior_standards.json"
SECTIONAL_STANDARDS_PATH = ROOT / "data" / "sectional_standards.json"
NATIONAL_STANDARDS_PATH = ROOT / "data" / "national_standards.json"
ADVANCED_STANDARDS_PATH = ROOT / "data" / "advanced_standards.json"


def load_motivational_catalog(path: Path = MOTIVATIONAL_STANDARDS_PATH) -> dict:
    """Load the course -> gender -> age band -> event -> tier catalog."""
    if not path.exists():
        return {}
    data = json.loads(path.read_text(encoding="utf-8"))
    return data.get("standards", {})


def load_azsi_catalog(path: Path = AZSI_STANDARDS_PATH) -> dict:
    """Load the AZSI course -> gender -> age band -> event -> {state, regional} catalog."""
    if not path.exists():
        return {}
    data = json.loads(path.read_text(encoding="utf-8"))
    return data.get("standards", {})


def load_azsi_senior_catalog(path: Path = AZSI_SENIOR_STANDARDS_PATH) -> dict:
    """Load the AZSI Senior course -> gender -> event -> {state, regional} catalog.

    Unlike the Age Group catalog there is no age-band level: Senior is one cut per
    event/course/gender, applied to ages 15-18 (see SENIOR_AGE_MIN/MAX).
    """
    if not path.exists():
        return {}
    data = json.loads(path.read_text(encoding="utf-8"))
    return data.get("standards", {})


def load_sectional_meets(path: Path = SECTIONAL_STANDARDS_PATH) -> list[dict]:
    """Load the Speedo Sectional meets as an ordered list of {key, name, standards} dicts.

    Each meet keeps its own course -> gender -> event -> {qualifying} catalog; the two meets are
    NOT merged so the app can label "Four Corners" and "Western Region Summer" distinctly.
    """
    if not path.exists():
        return []
    data = json.loads(path.read_text(encoding="utf-8"))
    meets = []
    for key, meet in data.get("meets", {}).items():
        meets.append({
            "key": key,
            "name": meet.get("name", key),
            "standards": meet.get("standards", {}),
            "url": meet.get("url"),
        })
    return meets


def load_national_meets(path: Path = NATIONAL_STANDARDS_PATH) -> list[dict]:
    """Load the national elite meets as an ordered list of {key, name, kind, standards, ...} dicts.

    ``kind`` is "age_bracket" (Futures, Toyota Nationals -- standards nest an extra bracket level,
    course -> gender -> bracket -> event -> {qualifying}) or "flat_bonus" (Summer/Winter Juniors,
    U.S. Open -- course -> gender -> event -> {qualifying, bonus}, no bracket). flat_bonus meets
    also carry "age_ceiling" (the Qualifying tier's age cap, None if age-open) and
    "bonus_age_ceiling" (the Bonus tier's own cap -- U.S. Open's differs from its Qualifying cap:
    the Qualifying tier is age-open but Bonus is 18-and-under only). Each meet keeps its own
    catalog, never merged, so lookup() can name them individually.
    """
    if not path.exists():
        return []
    data = json.loads(path.read_text(encoding="utf-8"))
    meets = []
    for key, meet in data.get("meets", {}).items():
        meets.append({
            "key": key,
            "name": meet.get("name", key),
            "kind": "age_bracket" if "age_brackets" in meet else "flat_bonus",
            "standards": meet.get("standards", {}),
            "age_ceiling": meet.get("age_ceiling"),
            "bonus_age_ceiling": meet.get("bonus_age_ceiling"),
            "url": meet.get("url"),
        })
    return meets


def load_source_url(path: Path) -> str | None:
    """The source document/page URL recorded in a dataset's own JSON `source` metadata."""
    if not path.exists():
        return None
    return json.loads(path.read_text(encoding="utf-8")).get("source", {}).get("url")


def load_advanced_sources(path: Path = ADVANCED_STANDARDS_PATH) -> list[dict]:
    """Return only the source-attribution entries from data/advanced_standards.json.

    SUPERSEDED for the live "Beyond AAAA" ladder: next_advanced_target() now builds that ladder
    from data/sectional_standards.json + data/national_standards.json (see advanced_ladder_rungs).
    The file's "cuts" are no longer read by any code path -- they are archival: its national rungs
    duplicate national_standards.json's 18-&-Under cuts exactly, and its "Speedo Sectionals" rung is
    the national *maximum* sectional reference (2026_speedosectionals_timestandards_max.pdf), a
    distinct non-Arizona standard the newer datasets don't carry. The file is retained (not deleted)
    only as the sole record of that max reference and for the handful of source-attribution URLs it
    contributes that aren't already attributed by the newer datasets (deduplicated below)."""
    if not path.exists():
        return []
    return json.loads(path.read_text(encoding="utf-8")).get("sources", [])


# Arizona LSC (AZSI) qualifying cuts, generated by scripts/extract_azsi_standards.py from the
# official 2025-2026 State and Regional PDFs. Two catalogs, both {state, regional} per cell,
# with State faster than Regional in every event (meeting the State cut removes Regional
# eligibility -- the swimmer swims up to State -- which lookup() reports as "State met"):
#   AZSI_STANDARDS         data/azsi_standards.json         course -> gender -> age band -> event
#                          Age Group bands 10 & under / 11-12 / 13-14 (ages 14 and under).
#   AZSI_SENIOR_STANDARDS  data/azsi_senior_standards.json  course -> gender -> event (no band)
#                          One Senior cut per event, applied to ages 15-18 (SENIOR_AGE_MIN/MAX).
# Together they cover ages 10-&-under through 18 with no gap or overlap at the 14/15 boundary.
#
# Speedo Sectionals (USA Swimming Championship Series) layer on top for AZ swimmers, age-open
# (the meet flyers gate purely on qualifying time, not age), from data/sectional_standards.json
# (generated by scripts/extract_sectional_standards.py). Two distinct meets -- Four Corners Spring
# and Western Region Summer -- each course -> gender -> event -> {qualifying}, kept separate so
# lookup() can name them individually. These are a tier above LSC (zone/section level), so they
# report on their own StandardResult.sectional_summary line rather than folding into lsc_summary.
#
# National elite standards (USA Swimming championship series) layer on top for ANY state/LSC --
# not Arizona-scoped -- from data/national_standards.json (generated by
# scripts/extract_national_standards.py). Five meets: Futures and Toyota Nationals (age-bracket
# shape, no meet-wide age gate) and Summer Juniors, Winter Juniors, and U.S. Open (flat-plus-bonus
# shape, each carrying its own age_ceiling/bonus_age_ceiling -- see load_national_meets). Reported
# on their own StandardResult.national_summary line, named individually per meet like Sectionals.
MOTIVATIONAL_STANDARDS = load_motivational_catalog()
AZSI_STANDARDS = load_azsi_catalog()
AZSI_SENIOR_STANDARDS = load_azsi_senior_catalog()
SECTIONAL_MEETS = load_sectional_meets()
NATIONAL_MEETS = load_national_meets()
ADVANCED_SOURCES = load_advanced_sources()
# Only add attributions not already present -- the newer sectional/national datasets already cite
# the Futures/Junior/Toyota PDFs, so extending blindly printed duplicate lines in the sources report.
_attributed_urls = {source.get("url") for source in SOURCES}
SOURCES.extend(source for source in ADVANCED_SOURCES if source.get("url") not in _attributed_urls)

# Source URLs read from each dataset's own JSON `source` metadata, used to make every displayed
# standard label a checkable link to the document that number came from. Motivational and AZSI
# record a single source URL; the AZSI datasets point at the azswimming standards page (the specific
# State/Regional PDFs are recorded only as filenames there). Sectional/national record a full URL
# per meet, so those are keyed by meet name.
MOTIVATIONAL_SOURCE_URL = load_source_url(MOTIVATIONAL_STANDARDS_PATH)
AZSI_SOURCE_URL = load_source_url(AZSI_STANDARDS_PATH)
AZSI_SENIOR_SOURCE_URL = load_source_url(AZSI_SENIOR_STANDARDS_PATH)
MEET_URL_BY_NAME = {
    meet["name"]: meet["url"]
    for meet in [*SECTIONAL_MEETS, *NATIONAL_MEETS]
    if meet.get("url")
}


def meet_sources_in(text: str | None) -> list[dict[str, str]]:
    """Source links for every sectional/national meet whose name appears in a summary line. Meet
    names are full and distinct (none is a substring of another), so a simple containment check
    resolves the exact meets that contributed to this line."""
    if not text:
        return []
    return [
        {"label": name, "url": url}
        for name, url in MEET_URL_BY_NAME.items()
        if name in text
    ]


# The LSCs this app has qualifying-time standards configured for. Every AZSI/Sectional gate below
# keys off this one set (rather than scattered "== AZ" literals), and team-code auto-detection asks
# the same question through has_lsc_standards(), so wiring up a new LSC means adding its code here
# plus its catalogs -- not hunting down individual checks.
LSC_WITH_STANDARDS = frozenset({"AZ"})


def has_lsc_standards(state: str | None) -> bool:
    """True when `state` names an LSC this app has configured AZSI/Sectional standards for."""
    return bool(state) and state.strip().upper() in LSC_WITH_STANDARDS


def motivational_standards(
    course: str | None, gender: str | None, band: str | None, event_key: str
) -> dict[str, str] | None:
    if not (course and gender and band and event_key):
        return None
    return (
        MOTIVATIONAL_STANDARDS.get(course, {})
        .get(gender, {})
        .get(band, {})
        .get(event_key)
    )


def azsi_standard(
    course: str | None, gender: str | None, band: str | None, event_key: str
) -> dict[str, str] | None:
    if not (course and gender and band and event_key):
        return None
    return (
        AZSI_STANDARDS.get(course, {})
        .get(gender, {})
        .get(band, {})
        .get(event_key)
    )


def is_senior_age(age: int | None) -> bool:
    """True for ages the AZSI Senior standards cover (15-18); Age Group covers 14 and under."""
    return age is not None and SENIOR_AGE_MIN <= age <= SENIOR_AGE_MAX


def azsi_senior_standard(
    course: str | None, gender: str | None, event_key: str
) -> dict[str, str] | None:
    if not (course and gender and event_key):
        return None
    return (
        AZSI_SENIOR_STANDARDS.get(course, {})
        .get(gender, {})
        .get(event_key)
    )


# The next AZSI band above a given one, for the "also meets the next band" bonus check. Age Group
# steps within its own three-band table (10 & under -> 11-12 -> 13-14); 13-14 then crosses into the
# separately-shaped, band-less Senior catalog -- a different lookup (azsi_senior_standard), not
# another row in the same table -- so this is NOT a uniform "+1 band" step. Senior itself has nothing
# above it within this app's 18-and-under benchmark scope.
AZSI_NEXT_BAND = {
    "10 & under": "11-12",
    "11-12": "13-14",
    "13-14": "Senior",
}


def azsi_next_band_standard(
    course: str | None, gender: str | None, band_label: str | None, event_key: str
) -> tuple[str | None, dict[str, str] | None]:
    """The AZSI cut one band up from ``band_label`` for the same event, as (next_label, cell).

    Returns (None, None) when there is no next band -- Senior (the top), or any unmapped label. The
    13-14 -> Senior step reads the flat, band-less Senior catalog rather than the Age Group table,
    so callers get the right cut without knowing the two datasets are shaped differently.
    """
    next_label = AZSI_NEXT_BAND.get(band_label or "")
    if next_label is None:
        return None, None
    if next_label == "Senior":
        return next_label, azsi_senior_standard(course, gender, event_key)
    return next_label, azsi_standard(course, gender, next_label, event_key)


def azsi_next_band_state_bonus(
    course: str | None, gender: str | None, band_label: str | None, event_key: str, seed_seconds: float
) -> str | None:
    """A note that the swimmer also clears the next age band's (faster) State cut, or None.

    Only meaningful once the swimmer has met their own band's State cut -- the caller gates on that
    -- since the next band's standard is always faster; beating it too is a genuine bonus. None when
    there is no next band, no cut configured there, or the seed does not beat it.
    """
    next_label, cell = azsi_next_band_standard(course, gender, band_label, event_key)
    if not cell or "state" not in cell:
        return None
    next_state = parse_time(cell["state"])
    if next_state is None or seed_seconds > next_state:
        return None
    return f"also meets {next_label} State standard ({cell['state']})"


def _nearest_unmet_rung(rungs: list[tuple[str, str, float]], seed_seconds: float) -> str | None:
    """Walk rungs slowest (easiest) to fastest and return "{name(s)} {time_str}" for the first --
    i.e. nearest -- one still unmet, joining every rung that ties on the exact same cut string.
    None when every rung is already met (the caller reports "met" instead) or the list is empty.

    Same "find nearest unmet, join ties" approach as next_advanced_target()'s walk over
    advanced_ladder_rungs() (the "Beyond AAAA" line) -- deliberately a separate, smaller helper
    rather than calling into that one, since sectional/national must stay their own distinct rows
    and next_advanced_target()/advanced_ladder_rungs() are not touched by this.
    """
    for _name, time_str, secs in rungs:
        if seed_seconds > secs:
            names = [name for name, t, _ in rungs if t == time_str]
            return f"{' / '.join(names)} {time_str}"
    return None


def sectional_summary_line(
    course: str | None, gender: str | None, event_key: str, seed_seconds: float
) -> str | None:
    """Single collapsed Speedo Sectional status for an event, or None if neither meet offers it.

    Both meets' qualifying cuts are combined into one difficulty-ordered ladder (same shape as
    advanced_ladder_rungs()) and only the single nearest unmet cut is reported, tied meets joined
    with "/" -- e.g. Four Corners and Western Region publish the identical 2026 AZ cut for most
    events, which used to print as two redundant identical segments on one line. "met" once every
    applicable meet's cut is beaten (no restated number, same convention as AZSI). Only meets that
    actually list the event contribute -- e.g. the Spring meet omits the 50s of stroke, so an event
    with only a Summer cut collapses to that one meet's name, same as before.
    """
    if not (course and gender and event_key):
        return None
    gender_label = "Girls" if gender == "girls" else "Boys"
    rungs: list[tuple[str, str, float]] = []
    for meet in SECTIONAL_MEETS:
        cell = meet["standards"].get(course, {}).get(gender, {}).get(event_key)
        if not cell or "qualifying" not in cell:
            continue
        cut = parse_time(cell["qualifying"])
        if cut is None:
            continue
        rungs.append((meet["name"], cell["qualifying"], cut))
    if not rungs:
        return None
    rungs.sort(key=lambda rung: rung[2], reverse=True)  # slowest (easiest) first
    nearest = _nearest_unmet_rung(rungs, seed_seconds)
    tail = f"next {nearest}" if nearest else "met"
    return f"Sectional {gender_label} {course} -- {tail}"


def age_bracket(age: int | None) -> str | None:
    """Map a swimmer's age to the Futures/Toyota Nationals bracket. None if age is unknown --
    the bracket determines which cutoff to compare against, so an unknown age can't be resolved
    (unlike Sectionals, which has only one cutoff and needs no bracket)."""
    if age is None:
        return None
    return "18 & Under" if age <= 18 else "19 & Over"


def national_summary_line(
    course: str | None, gender: str | None, event_key: str, seed_seconds: float, age: int | None
) -> str | None:
    """Single collapsed national elite status for an event, or None if no meet offers it.

    Every meet (Futures, Toyota Nationals, Summer/Winter Juniors, U.S. Open) contributes into one
    difficulty-ordered ladder (same shape as advanced_ladder_rungs()), and only the single nearest
    unmet cut is reported, tied meets joined with "/" -- never merged meet-by-meet into one long
    line. Futures/Toyota Nationals are age-bracket meets (18 & Under / 19 & Over) -- an unknown age
    can't be resolved to a bracket, so those meets contribute no rung at all rather than guessing.
    The flat-plus-bonus meets each carry their own age_ceiling (Summer/Winter Juniors: 18,
    meet-wide; U.S. Open: None, age-open) and bonus_age_ceiling (independent of age_ceiling for
    U.S. Open, whose Bonus tier alone is 18-and-under) -- an unknown age is treated as
    not-yet-disqualified (rung included), matching how the rest of this app treats unresolved ages
    as "can't rule out" rather than "assume ineligible".

    Qualifying/Bonus, collapsed: unlike advanced_ladder_rungs() (which only ever reads
    "qualifying"), a flat-plus-bonus meet contributes UP TO TWO rungs here -- its own Bonus cut
    (the easier one) and its own Qualifying cut (the harder one) -- so the meet's internal
    Qualifying/Bonus structure survives being folded into the shared ladder instead of collapsing
    to a single number. Sorting the combined ladder slowest-first and walking for the first unmet
    rung then does the right thing automatically: a swimmer who has met a meet's Bonus but not its
    Qualifying has that Bonus rung skipped (already met) and lands on the next genuinely unmet rung
    -- which may be that same meet's own Qualifying, or a nearer cut from a different meet entirely
    -- with no special-casing needed beyond building the two rungs. This is the same convention
    AZSI's State/Regional split and Sectional use throughout: a met tier's number is never
    restated, so what surfaces is always the next real target, never a "you already have X" recap.
    """
    if not (course and gender and event_key):
        return None
    gender_label = "Girls" if gender == "girls" else "Boys"
    rungs: list[tuple[str, str, float]] = []
    bracket = age_bracket(age)
    for meet in NATIONAL_MEETS:
        genders = meet["standards"].get(course, {}).get(gender, {})
        if meet["kind"] == "age_bracket":
            if bracket is None:
                continue
            cell = genders.get(bracket, {}).get(event_key)
            if not cell or "qualifying" not in cell:
                continue
            cut = parse_time(cell["qualifying"])
            if cut is None:
                continue
            rungs.append((f"{meet['name']} ({bracket})", cell["qualifying"], cut))
        else:
            age_ceiling = meet.get("age_ceiling")
            if age_ceiling is not None and age is not None and age > age_ceiling:
                continue
            cell = genders.get(event_key)
            if not cell or "qualifying" not in cell:
                continue
            # Qualifying rung: always labeled "(Qualifying)", even when Bonus doesn't apply to this
            # swimmer's age -- same convention the old per-meet text used ("target Qualifying X"
            # regardless of Bonus eligibility), so the label stays meaningful on its own line.
            qualifying_cut = parse_time(cell["qualifying"])
            if qualifying_cut is not None:
                rungs.append((f"{meet['name']} (Qualifying)", cell["qualifying"], qualifying_cut))
            bonus_age_ceiling = meet.get("bonus_age_ceiling")
            bonus_allowed = "bonus" in cell and not (
                bonus_age_ceiling is not None and age is not None and age > bonus_age_ceiling
            )
            if bonus_allowed:
                bonus_cut = parse_time(cell["bonus"])
                if bonus_cut is not None:
                    rungs.append((f"{meet['name']} (Bonus)", cell["bonus"], bonus_cut))
    if not rungs:
        return None
    rungs.sort(key=lambda rung: rung[2], reverse=True)  # slowest (easiest) first
    nearest = _nearest_unmet_rung(rungs, seed_seconds)
    tail = f"next {nearest}" if nearest else "met"
    return f"National {gender_label} {course} -- {tail}"


def achieved_tier(seed_seconds: float, standards: dict[str, str]) -> tuple[str | None, str | None]:
    ordered = list(reversed(TIER_ORDER))  # AAAA (fastest) -> B
    for idx, tier in enumerate(ordered):
        cut = parse_time(standards[tier])
        if cut is not None and seed_seconds <= cut:
            next_tier = ordered[idx - 1] if idx > 0 else None
            return tier, next_tier
    return None, "B"


def unconfigured_reason(gender: str | None, course: str | None, band: str | None) -> str:
    if gender is None:
        return "USA-S: could not determine gender from the event name"
    if course is None:
        return "USA-S: could not determine course from the event name"
    if band is None:
        return "USA-S: not configured for this swimmer age"
    return "USA-S: standard not configured for this event"


def lookup(event_name: str, seed_time: str, state: str = "AZ", age: str | int | None = None) -> StandardResult:
    event_key = canonical_event_key(event_name)
    seed_seconds = parse_time(seed_time)
    swimmer_age = parse_age(age)
    gender = event_gender(event_name)
    course = event_course(event_name)
    band = age_band(swimmer_age)

    if seed_seconds is None:
        return StandardResult(
            event_key,
            "USA-S: seed time not parseable",
            "LSC: seed time not parseable",
            None,
            "Standards confidence: not calculated",
        )

    usa_standards = motivational_standards(course, gender, band, event_key)
    # Only genuine gaps go on the confidence line now (a "verified" restatement is redundant with the
    # summary lines themselves, which already show the met tier / cut). Empty -> no line at all.
    gap_parts: list[str] = []
    advanced_summary: str | None = None
    sources: dict[str, list[dict[str, str]]] = {}

    if usa_standards:
        gender_label = "Girls" if gender == "girls" else "Boys"
        source_label = f"USA-S {band} {gender_label} {course}"
        if MOTIVATIONAL_SOURCE_URL:
            sources["usa"] = [{"label": source_label, "url": MOTIVATIONAL_SOURCE_URL}]
        tier, next_tier = achieved_tier(seed_seconds, usa_standards)
        if tier:
            if next_tier:
                usa_summary = f"{source_label}: {tier}; next {next_tier} {usa_standards[next_tier]}"
            else:
                usa_summary = f"{source_label}: AAAA"
                if gender == "girls" and course == "LCM":
                    advanced_summary = next_advanced_target(
                        course, gender, event_key, seed_seconds, swimmer_age, state
                    )
        else:
            usa_summary = f"{source_label}: below B; B target {usa_standards['B']}"
    else:
        usa_summary = unconfigured_reason(gender, course, band)
        gap_parts.append("USA-S not configured")

    # Arizona LSC layer: AZ only. Age Group bands (10 & under, 11-12, 13-14) cover ages 14 and
    # under; the flat Senior catalog covers ages 15-18 (is_senior_age). Age Group is tried first
    # -- for 15-18 the age_band() result ("15-16"/"17-18") is absent from the Age Group catalog
    # so azsi_standard() returns None, and the Senior lookup supplies the cut instead. Both share
    # the {state, regional} shape, so the summary logic below is identical; only the label band
    # differs ("Senior" vs the age band).
    azsi = azsi_standard(course, gender, band, event_key) if has_lsc_standards(state) else None
    azsi_band_label = band
    if azsi is None and has_lsc_standards(state) and is_senior_age(swimmer_age):
        azsi = azsi_senior_standard(course, gender, event_key)
        azsi_band_label = "Senior"
    if azsi and "state" in azsi and "regional" in azsi:
        gender_label = "Girls" if gender == "girls" else "Boys"
        azsi_label = f"AZSI {azsi_band_label} {gender_label} {course}"
        azsi_url = AZSI_SENIOR_SOURCE_URL if azsi_band_label == "Senior" else AZSI_SOURCE_URL
        if azsi_url:
            sources["lsc"] = [{"label": azsi_label, "url": azsi_url}]
        state_cut = parse_time(azsi["state"])
        regional_cut = parse_time(azsi["regional"])
        if state_cut is not None and seed_seconds <= state_cut:
            # Arizona rule: meeting the State cut removes Regional eligibility for that event
            # entirely (the swimmer swims up to State), so the Regional value is dropped here --
            # not just redundant, showing it would misstate an eligibility the swimmer no longer
            # has.
            # "met" already says everything actionable -- restating the beaten cutoff is noise, the
            # same convention Motivational uses (AAAA never re-prints the AAAA cut). Numbers appear
            # only for genuinely unmet targets, plus the next-band bonus below (new information).
            lsc_summary = f"{azsi_label}: State met"
            # Bonus: having met their own State cut, is the swimmer already under the next age
            # band's (faster) State cut too? Only checked here, in the State-met branch, so it never
            # adds noise for a swimmer still chasing their own band. azsi_band_label carries the
            # current band ("10 & under"/"11-12"/"13-14"/"Senior"); a Senior swimmer has no next
            # band and gets nothing.
            next_band_bonus = azsi_next_band_state_bonus(
                course, gender, azsi_band_label, event_key, seed_seconds
            )
            if next_band_bonus:
                lsc_summary = f"{lsc_summary}; {next_band_bonus}"
        elif regional_cut is not None and seed_seconds <= regional_cut:
            # Same convention: Regional's beaten cutoff is dropped; the unmet State target keeps its
            # number because that is the goal still ahead of the swimmer.
            lsc_summary = f"{azsi_label}: Regional met; State target {azsi['state']}"
        else:
            lsc_summary = f"{azsi_label}: target State {azsi['state']}, Regional {azsi['regional']}"
    else:
        lsc_summary = "LSC: standards not configured for this state/event"
        gap_parts.append("LSC not configured")

    # Speedo Sectional layer: AZ only, AGE-OPEN. The Four Corners Spring and Western Region Summer
    # meet flyers both define eligibility as "open to all athletes who ... have met the appropriate
    # qualifying times" -- registration plus an eligible LSC plus the time, with no age floor or
    # ceiling. So this is deliberately NOT gated to the 15-18 Senior range (that would be
    # convenience, not the published rule): any AZ swimmer whose event has a Sectional cut sees the
    # target, including ages the USA-S/AZSI layers can't classify (e.g. 19+). Reported on its own
    # line because Sectionals sit a tier above LSC; the two meets are named individually so they
    # never collapse into a generic "Sectional". Left off the confidence line to keep it stable.
    sectional_summary: str | None = None
    if has_lsc_standards(state):
        sectional_summary = sectional_summary_line(course, gender, event_key, seed_seconds)

    # National elite layer: ANY state/LSC (not Arizona-scoped, unlike AZSI/Sectional above) --
    # these are national championship series open to any USA Swimming member. Age gating is
    # handled inside national_summary_line() per meet (Futures/Toyota Nationals need a resolvable
    # bracket; each flat-plus-bonus meet carries its own age_ceiling/bonus_age_ceiling), not here.
    national_summary = national_summary_line(course, gender, event_key, seed_seconds, swimmer_age)

    # Per-meet source links for every line that names a meet (sectional/national, and the advanced
    # "Beyond AAAA" line, which cites the sectional/national meet its next target belongs to).
    for line_name, summary in (
        ("sectional", sectional_summary),
        ("national", national_summary),
        ("advanced", advanced_summary),
    ):
        meet_sources = meet_sources_in(summary)
        if meet_sources:
            sources[line_name] = meet_sources

    # Confidence line reduced to genuine gaps only; when everything resolved it is omitted entirely
    # rather than restating the obvious ("verified").
    confidence_summary = f"Standards confidence: {', '.join(gap_parts)}" if gap_parts else ""

    return StandardResult(
        event_key,
        usa_summary,
        lsc_summary,
        advanced_summary,
        confidence_summary,
        sectional_summary,
        national_summary,
        sources,
    )


def advanced_ladder_rungs(
    course: str | None, gender: str | None, event_key: str, age: int | None, state: str
) -> list[tuple[str, str, float]]:
    """The difficulty-ordered elite ladder beyond Motivational AAAA for one event, built from the
    live AZ Sectional and national championship datasets -- NOT the legacy data/advanced_standards.json.

    Rungs come from: the AZ Speedo Sectionals (Four Corners Spring / Western Region Summer, the
    real Western-Region meets AZ swimmers actually attend -- AZ swimmers only, since we have no
    other section's cuts), and the national championship meets (any state). Each meet contributes
    its qualifying cut for this course/gender/event (and, for the age-bracket meets, the age's
    bracket). Returned sorted slowest-first, i.e. easiest-to-hardest, so the caller can surface the
    next cut a swimmer still has to earn.
    """
    if not (course and gender and event_key):
        return []
    rungs: list[tuple[str, str, float]] = []

    def add(name: str, cell: dict | None) -> None:
        if not cell or not cell.get("qualifying"):
            return
        secs = parse_time(cell["qualifying"])
        if secs is not None:
            rungs.append((name, cell["qualifying"], secs))

    if has_lsc_standards(state):
        for meet in SECTIONAL_MEETS:
            add(meet["name"], meet["standards"].get(course, {}).get(gender, {}).get(event_key))

    bracket = age_bracket(age)
    for meet in NATIONAL_MEETS:
        genders = meet["standards"].get(course, {}).get(gender, {})
        if meet["kind"] == "age_bracket":
            if bracket is None:
                continue
            add(meet["name"], genders.get(bracket, {}).get(event_key))
        else:
            ceiling = meet.get("age_ceiling")
            if ceiling is not None and age is not None and age > ceiling:
                continue
            add(meet["name"], genders.get(event_key))

    rungs.sort(key=lambda rung: rung[2], reverse=True)  # slowest (easiest) first
    return rungs


def next_advanced_target(
    course: str | None, gender: str | None, event_key: str, seed_seconds: float, age: int | None, state: str
) -> str | None:
    rungs = advanced_ladder_rungs(course, gender, event_key, age, state)
    for _name, time_str, secs in rungs:
        if seed_seconds > secs:
            # The next unmet (easiest still-unbeaten) rung, matching every other benchmark line's
            # "next X" pattern (e.g. "AA; next AAA 39.09"). When several meets share that exact
            # cut -- Four Corners and Western Region publish identical AZ Sectional times -- name
            # them all so it's clear which meets the target belongs to.
            names = [name for name, t, _ in rungs if t == time_str]
            return f"Beyond AAAA: next {' / '.join(names)} {time_str}"
    if rungs:
        return "Advanced standards loaded; swimmer has met all configured targets"
    return "Advanced cuts beyond AAAA are not configured for this event yet"
