"""Source-tracked time-standard lookup for calendar benchmark notes.

USA Swimming motivational standards are loaded from ``data/motivational_standards.json``
(generated by ``scripts/extract_motivational_standards.py`` from the official age-group
PDF). The catalog covers both genders, all three courses (SCY/SCM/LCM), and all five
two-year age groups (10 & under through 17-18). Swimmer gender and course are read off
the event name; the swimmer's age is mapped to its two-year band. A separate Arizona LSC
table (AZSI) and an advanced post-AAAA ladder (``data/advanced_standards.json``) layer on
top for the cases they cover.
"""

from __future__ import annotations

from dataclasses import dataclass
import json
from pathlib import Path
import re


SOURCES = [
    {
        "name": "USA Swimming 2024-2028 Motivational Standards (two-year age group)",
        "url": "https://www.usaswimming.org/times/popular-resources/motivational-times",
    },
    {
        "name": "AZSI 2025-2026 Age Group State Qualifying Time Standards",
        "url": "https://www.azswimming.org/azswimming/UserFiles/File/azsi-age-group-state-qualifying-time-standards-2025-2026_080831.pdf",
    },
    {
        "name": "AZSI 2025-2026 Age Group Regional Qualifying Time Standards",
        "url": "https://www.azswimming.org/azswimming/UserFiles/File/azsi-age-group-regional-qualifying-time-standards-2025-2026_068948.pdf",
    },
]

# Slowest -> fastest.
TIER_ORDER = ["B", "BB", "A", "AA", "AAA", "AAAA"]

# Distances longest-first so the regex prefers "1650" over the "50" inside it.
KNOWN_DISTANCES = ("1650", "1500", "1000", "800", "500", "400", "200", "100", "50", "25")


@dataclass(frozen=True)
class StandardResult:
    event_key: str
    usa_summary: str
    lsc_summary: str
    advanced_summary: str | None
    confidence_summary: str


def parse_time(value: str) -> float | None:
    value = value.strip().upper().rstrip("YLS")
    if value in {"", "NT"}:
        return None
    parts = value.split(":")
    try:
        if len(parts) == 1:
            return float(parts[0])
        if len(parts) == 2:
            return int(parts[0]) * 60 + float(parts[1])
    except ValueError:
        return None
    return None


def format_time(seconds: float) -> str:
    minutes = int(seconds // 60)
    rest = seconds - minutes * 60
    if minutes:
        return f"{minutes}:{rest:05.2f}"
    return f"{rest:.2f}"


def canonical_event_key(event_name: str) -> str:
    """Normalize an event name to a '<distance> <stroke>' key, e.g. '200 free', '400 im'.

    Age-group tokens that contain digits ('11-12', '12 & Under', '13 & Over') are stripped
    first so they can't be mistaken for the event distance, which otherwise trips up the
    longer freestyle distances (e.g. the '50' inside '1650').
    """
    text = re.sub(r"\s+", " ", event_name.lower())
    text = re.sub(r"\d+\s*&\s*(?:under|over)", " ", text)
    text = re.sub(r"\b\d{1,2}\s*-\s*\d{1,2}\b", " ", text)

    distance = None
    match = re.search(r"\b(" + "|".join(KNOWN_DISTANCES) + r")\b", text)
    if match:
        distance = match.group(1)

    if "relay" in text:
        stroke = "medley relay" if "medley" in text or "med-r" in text else "free relay"
    elif "free" in text:
        stroke = "free"
    elif "back" in text:
        stroke = "back"
    elif "breast" in text:
        stroke = "breast"
    elif "fly" in text or "butterfly" in text:
        stroke = "fly"
    elif re.search(r"\bim\b", text) or "individual medley" in text or "medley" in text:
        stroke = "im"
    else:
        stroke = None

    if distance and stroke:
        return f"{distance} {stroke}"
    return text.strip()


def event_gender(event_name: str) -> str | None:
    text = event_name.lower()
    if re.search(r"\b(girls|women)\b", text):
        return "girls"
    if re.search(r"\b(boys|men)\b", text):
        return "boys"
    return None


def event_course(event_name: str) -> str | None:
    """Read the pool course off the event name (Hy-Tek wording: 'LC Meter', 'SC Meter', 'SC Yard')."""
    text = event_name.lower()
    if "yard" in text or re.search(r"\bscy\b", text):
        return "SCY"
    if re.search(r"\bsc\s*meter", text) or re.search(r"\bscm\b", text):
        return "SCM"
    if re.search(r"\blc\s*meter", text) or re.search(r"\blcm\b", text) or "long course" in text:
        return "LCM"
    return None


def parse_age(age: str | int | None) -> int | None:
    if isinstance(age, int):
        return age
    match = re.search(r"\d{1,2}", str(age or ""))
    return int(match.group(0)) if match else None


def age_band(age: int | None) -> str | None:
    """Map a swimmer's actual age to its USA Swimming two-year motivational band.

    Returns None for ages the motivational standards do not cover (19 and older), so the
    caller reports 'not configured' rather than comparing against an inapplicable group.
    """
    if age is None:
        return None
    if age <= 10:
        return "10 & under"
    if age <= 12:
        return "11-12"
    if age <= 14:
        return "13-14"
    if age <= 16:
        return "15-16"
    if age <= 18:
        return "17-18"
    return None


ROOT = Path(__file__).resolve().parents[1]
MOTIVATIONAL_STANDARDS_PATH = ROOT / "data" / "motivational_standards.json"
AZSI_STANDARDS_PATH = ROOT / "data" / "azsi_standards.json"
ADVANCED_STANDARDS_PATH = ROOT / "data" / "advanced_standards.json"


def load_motivational_catalog(path: Path = MOTIVATIONAL_STANDARDS_PATH) -> dict:
    """Load the course -> gender -> age band -> event -> tier catalog."""
    if not path.exists():
        return {}
    data = json.loads(path.read_text(encoding="utf-8"))
    return data.get("standards", {})


def load_azsi_catalog(path: Path = AZSI_STANDARDS_PATH) -> dict:
    """Load the AZSI course -> gender -> age band -> event -> {state, regional} catalog."""
    if not path.exists():
        return {}
    data = json.loads(path.read_text(encoding="utf-8"))
    return data.get("standards", {})


def load_advanced_catalog(path: Path = ADVANCED_STANDARDS_PATH) -> tuple[list[dict], dict[str, list[dict[str, str]]]]:
    if not path.exists():
        return [], {}
    data = json.loads(path.read_text(encoding="utf-8"))
    sources = data.get("sources", [])
    cuts = data.get("cuts", {})
    normalized: dict[str, list[dict[str, str]]] = {}
    for event_name, rows in cuts.items():
        key = canonical_event_key(event_name)
        normalized[key] = [row for row in rows if row.get("time")]
        normalized[key].sort(key=lambda row: parse_time(row["time"]) or -1, reverse=True)
    return sources, normalized


# Arizona LSC (AZSI) Age Group qualifying cuts, loaded from data/azsi_standards.json
# (generated by scripts/extract_azsi_standards.py from the official 2025-2026 State and
# Regional PDFs). Keyed course -> gender -> age band -> event -> {state, regional}, the same
# shape as MOTIVATIONAL_STANDARDS with {state, regional} in place of the tier dict. Covers all
# three courses (SCY/SCM/LCM), both genders, and the three Age Group bands (10 & under, 11-12,
# 13-14). State cuts are faster than Regional in every event; meeting the State cut removes
# Regional eligibility (the swimmer swims up to State), which lookup() reports as "State met".
# The 15-18 Senior standards are published in a separate AZSI document and are NOT included.
MOTIVATIONAL_STANDARDS = load_motivational_catalog()
AZSI_STANDARDS = load_azsi_catalog()
ADVANCED_SOURCES, ADVANCED_LADDER = load_advanced_catalog()
SOURCES.extend(ADVANCED_SOURCES)


def motivational_standards(
    course: str | None, gender: str | None, band: str | None, event_key: str
) -> dict[str, str] | None:
    if not (course and gender and band and event_key):
        return None
    return (
        MOTIVATIONAL_STANDARDS.get(course, {})
        .get(gender, {})
        .get(band, {})
        .get(event_key)
    )


def azsi_standard(
    course: str | None, gender: str | None, band: str | None, event_key: str
) -> dict[str, str] | None:
    if not (course and gender and band and event_key):
        return None
    return (
        AZSI_STANDARDS.get(course, {})
        .get(gender, {})
        .get(band, {})
        .get(event_key)
    )


def achieved_tier(seed_seconds: float, standards: dict[str, str]) -> tuple[str | None, str | None]:
    ordered = list(reversed(TIER_ORDER))  # AAAA (fastest) -> B
    for idx, tier in enumerate(ordered):
        cut = parse_time(standards[tier])
        if cut is not None and seed_seconds <= cut:
            next_tier = ordered[idx - 1] if idx > 0 else None
            return tier, next_tier
    return None, "B"


def unconfigured_reason(gender: str | None, course: str | None, band: str | None) -> str:
    if gender is None:
        return "USA-S: could not determine gender from the event name"
    if course is None:
        return "USA-S: could not determine course from the event name"
    if band is None:
        return "USA-S: not configured for this swimmer age"
    return "USA-S: standard not configured for this event"


def lookup(event_name: str, seed_time: str, state: str = "AZ", age: str | int | None = None) -> StandardResult:
    event_key = canonical_event_key(event_name)
    seed_seconds = parse_time(seed_time)
    swimmer_age = parse_age(age)
    gender = event_gender(event_name)
    course = event_course(event_name)
    band = age_band(swimmer_age)

    if seed_seconds is None:
        return StandardResult(
            event_key,
            "USA-S: seed time not parseable",
            "LSC: seed time not parseable",
            None,
            "Standards confidence: not calculated",
        )

    usa_standards = motivational_standards(course, gender, band, event_key)
    confidence_parts: list[str] = []
    advanced_summary: str | None = None

    if usa_standards:
        gender_label = "Girls" if gender == "girls" else "Boys"
        source_label = f"USA-S {band} {gender_label} {course}"
        tier, next_tier = achieved_tier(seed_seconds, usa_standards)
        if tier:
            if next_tier:
                usa_summary = f"{source_label}: {tier}; next {next_tier} {usa_standards[next_tier]}"
            else:
                usa_summary = f"{source_label}: AAAA"
                if gender == "girls" and course == "LCM":
                    advanced_summary = next_advanced_target(event_key, seed_seconds)
        else:
            usa_summary = f"{source_label}: below B; B target {usa_standards['B']}"
        confidence_parts.append("USA-S verified")
    else:
        usa_summary = unconfigured_reason(gender, course, band)
        confidence_parts.append("USA-S not configured")

    # Arizona LSC layer: AZ only, across the AZSI Age Group bands (10 & under, 11-12, 13-14),
    # both genders, and any course the source covers. Senior ages (15-18) are not in the AZSI
    # Age Group catalog, so azsi_standard() returns None and the LSC line reports not configured.
    azsi = azsi_standard(course, gender, band, event_key) if state.upper() == "AZ" else None
    if azsi and "state" in azsi and "regional" in azsi:
        gender_label = "Girls" if gender == "girls" else "Boys"
        azsi_label = f"AZSI {band} {gender_label} {course}"
        state_cut = parse_time(azsi["state"])
        regional_cut = parse_time(azsi["regional"])
        if state_cut is not None and seed_seconds <= state_cut:
            lsc_summary = f"{azsi_label}: State met; State {azsi['state']}, Regional {azsi['regional']}"
        elif regional_cut is not None and seed_seconds <= regional_cut:
            lsc_summary = f"{azsi_label}: Regional met; State target {azsi['state']}, Regional {azsi['regional']}"
        else:
            lsc_summary = f"{azsi_label}: target State {azsi['state']}, Regional {azsi['regional']}"
        confidence_parts.append("AZSI verified")
    else:
        lsc_summary = "LSC: standards not configured for this state/event"
        confidence_parts.append("LSC not configured")

    if advanced_summary and advanced_summary.startswith("Beyond AAAA"):
        confidence_parts.append("advanced verified")
    elif advanced_summary:
        confidence_parts.append("advanced partial")

    return StandardResult(
        event_key,
        usa_summary,
        lsc_summary,
        advanced_summary,
        f"Standards confidence: {', '.join(confidence_parts)}",
    )


def next_advanced_target(event_key: str, seed_seconds: float) -> str | None:
    remaining: list[dict[str, str]] = []
    for row in ADVANCED_LADDER.get(event_key, []):
        cut = parse_time(row["time"])
        if cut is not None and seed_seconds > cut:
            remaining.append(row)
    if remaining:
        next_row = remaining[0]
        then_rows = remaining[1:5]
        summary = f"Beyond AAAA: next {next_row['name']} {next_row['time']}"
        if then_rows:
            then = ", ".join(f"{row['name']} {row['time']}" for row in then_rows)
            summary = f"{summary}; then {then}"
        return summary
    if event_key in ADVANCED_LADDER:
        return "Advanced standards loaded; swimmer has met all configured targets"
    return "Advanced cuts beyond AAAA are not configured for this event yet"
